import { StyleSheet, Platform } from 'react-native';
import { AppColors } from '@/constants/colors';
import { AppFonts } from '@/constants/theme';

export const getLandingStyles = ({ 
    isMobile, 
    isTablet, 
    isDesktop, 
    initialHeight,
    scrollY 
}: { 
    isMobile: boolean, 
    isTablet: boolean, 
    isDesktop: boolean, 
    initialHeight: number,
    scrollY: number
}) => {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: '#fff',
        },
        scrollView: {
            flex: 1,
        },
        stickyHeader: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: 80,
            zIndex: 1000,
            justifyContent: 'center',
            paddingHorizontal: isDesktop ? 60 : 20,
        },
        stickyHeaderActive: {
            backgroundColor: 'rgba(15, 23, 42, 0.95)',
            borderBottomWidth: 1,
            borderBottomColor: 'rgba(255,255,255,0.1)',
        },
        headerContent: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            maxWidth: 1400,
            alignSelf: 'center',
            width: '100%',
        },
        headerLogo: {
            width: 120,
            height: 40,
        },
        navLinks: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 32,
        },
        navLink: {
            display: isMobile ? 'none' : 'flex',
        },
        navLinkText: {
            color: '#fff',
            fontFamily: AppFonts.medium,
            fontSize: 16,
            opacity: 0.8,
        },
        launchButton: {
            backgroundColor: AppColors.primary,
            paddingHorizontal: 24,
            paddingVertical: 12,
            borderRadius: 50,
        },
        launchButtonText: {
            color: '#fff',
            fontFamily: AppFonts.bold,
            fontSize: 14,
        },
        heroSection: {
            paddingTop: isMobile ? 120 : 160,
            paddingBottom: isMobile ? 60 : 100,
            paddingHorizontal: isDesktop ? 80 : 24,
            minHeight: initialHeight > 800 ? 800 : initialHeight,
            overflow: 'hidden',
            position: 'relative',
        },
        heroBackground: {
            ...StyleSheet.absoluteFillObject,
        },
        meshGradient: {
            position: 'absolute',
            width: 800,
            height: 800,
            borderRadius: 400,
        },
        heroContent: {
            maxWidth: 1400,
            alignSelf: 'center',
            width: '100%',
            zIndex: 10,
        },
        heroContentDesktop: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        heroTextContainer: {
            flex: 1.2,
            alignItems: isDesktop ? 'flex-start' : 'center',
        },
        heroBadge: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: 'rgba(249, 115, 22, 0.1)',
            borderWidth: 1,
            borderColor: 'rgba(249, 115, 22, 0.2)',
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 50,
            marginBottom: 32,
            gap: 8,
        },
        heroBadgeText: {
            color: AppColors.primary,
            fontFamily: AppFonts.bold,
            fontSize: 12,
            letterSpacing: 1.5,
        },
        heroTitle: {
            fontFamily: AppFonts.bold,
            fontSize: isDesktop ? 72 : 48,
            color: '#fff',
            lineHeight: isDesktop ? 82 : 56,
            marginBottom: 24,
            textAlign: isDesktop ? 'left' : 'center',
            letterSpacing: -1,
        },
        heroSubtitle: {
            fontFamily: AppFonts.regular,
            fontSize: 20,
            color: 'rgba(255,255,255,0.6)',
            lineHeight: 32,
            marginBottom: 48,
            maxWidth: 600,
            textAlign: isDesktop ? 'left' : 'center',
        },
        heroActions: {
            flexDirection: isMobile ? 'column' : 'row',
            alignItems: 'center',
            gap: 32,
        },
        heroPrimaryBtn: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: AppColors.primary,
            paddingHorizontal: 32,
            paddingVertical: 20,
            borderRadius: 100,
            shadowColor: AppColors.primary,
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.4,
            shadowRadius: 20,
        },
        heroPrimaryBtnText: {
            color: '#fff',
            fontFamily: AppFonts.bold,
            fontSize: 18,
            marginRight: 10,
        },
        platformBadges: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        platformText: {
            color: 'rgba(255,255,255,0.4)',
            fontFamily: AppFonts.medium,
            fontSize: 14,
        },
        heroVisualContainer: {
            flex: 1,
            height: 600,
            position: 'relative',
        },
        heroVisualMobile: {
            marginTop: 60,
            alignItems: 'center',
        },
        heroMockupPrimary: {
            position: 'absolute',
            top: 0,
            right: 0,
            zIndex: 2,
        },
        heroMockupSecondary: {
            position: 'absolute',
            top: 80,
            right: 220,
            zIndex: 1,
            opacity: 0.5,
        },
        statsBar: {
            paddingVertical: 60,
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: '#fff',
            borderBottomWidth: 1,
            borderBottomColor: '#f1f5f9',
        },
        statItem: {
            alignItems: 'center',
            paddingHorizontal: isDesktop ? 60 : 20,
        },
        statValue: {
            fontFamily: AppFonts.bold,
            fontSize: 40,
            color: AppColors.navy,
        },
        statLabel: {
            fontFamily: AppFonts.bold,
            fontSize: 12,
            color: AppColors.primary,
            marginTop: 4,
            letterSpacing: 2,
        },
        statDivider: {
            width: 1,
            height: 40,
            backgroundColor: '#e2e8f0',
        },
        showcaseSection: {
            paddingVertical: 120,
            backgroundColor: '#fff',
        },
        mosaicGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'center',
            gap: 40,
            paddingHorizontal: 24,
            maxWidth: 1600,
            alignSelf: 'center',
        },
        mosaicGridMobile: {
            flexDirection: 'column',
            alignItems: 'center',
        },
        mosaicItem: {
            width: isDesktop ? '22%' : isTablet ? '45%' : '100%',
        },
        sectionHeader: {
            alignItems: 'center',
            marginBottom: 80,
            paddingHorizontal: 24,
        },
        preTitleBadge: {
            backgroundColor: 'rgba(249, 115, 22, 0.05)',
            paddingHorizontal: 12,
            paddingVertical: 4,
            borderRadius: 4,
            marginBottom: 16,
        },
        preTitleText: {
            color: AppColors.primary,
            fontFamily: AppFonts.bold,
            fontSize: 12,
            letterSpacing: 2,
        },
        sectionTitle: {
            fontFamily: AppFonts.bold,
            fontSize: 42,
            color: AppColors.navy,
            textAlign: 'center',
            maxWidth: 800,
            lineHeight: 52,
        },
        sectionSubtitle: {
            fontFamily: AppFonts.regular,
            fontSize: 18,
            color: AppColors.textSecondary,
            textAlign: 'center',
            maxWidth: 700,
            marginTop: 20,
            lineHeight: 30,
        },
        featuresSection: {
            paddingVertical: 120,
            position: 'relative',
            overflow: 'hidden',
        },
        featuresBackground: {
            ...StyleSheet.absoluteFillObject,
        },
        bentoGrid: {
            maxWidth: 1400,
            alignSelf: 'center',
            width: '100%',
            paddingHorizontal: 24,
            gap: 24,
        },
        bentoGridDesktop: {
            flexDirection: 'row',
        },
        bentoCardLarge: {
            flex: 1.5,
            flexDirection: 'row',
            height: 500,
            padding: 60,
            paddingBottom: 0,
            overflow: 'hidden',
        },
        bentoCardContent: {
            flex: 1,
            justifyContent: 'center',
            paddingBottom: 60,
        },
        bentoVisual: {
            flex: 1,
            justifyContent: 'flex-end',
            alignItems: 'center',
            transform: [{ translateY: 60 }],
        },
        bentoRightCol: {
            flex: 1,
            gap: 24,
        },
        bentoCardSmall: {
            flex: 1,
            padding: 40,
            justifyContent: 'center',
        },
        bentoIconBox: {
            width: 64,
            height: 64,
            borderRadius: 16,
            backgroundColor: 'rgba(255,255,255,0.05)',
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: 24,
        },
        bentoTitle: {
            color: '#fff',
            fontFamily: AppFonts.bold,
            fontSize: 32,
            marginBottom: 16,
        },
        bentoDesc: {
            color: 'rgba(255,255,255,0.6)',
            fontFamily: AppFonts.regular,
            fontSize: 18,
            lineHeight: 28,
        },
        bentoTitleSmall: {
            color: '#fff',
            fontFamily: AppFonts.bold,
            fontSize: 24,
            marginBottom: 12,
        },
        bentoDescSmall: {
            color: 'rgba(255,255,255,0.5)',
            fontFamily: AppFonts.regular,
            fontSize: 16,
            lineHeight: 24,
        },
        ctaSection: {
            paddingVertical: 120,
            paddingHorizontal: 24,
            backgroundColor: '#fff',
        },
        ctaContainer: {
            maxWidth: 1400,
            alignSelf: 'center',
            width: '100%',
            padding: isDesktop ? 100 : 40,
            alignItems: 'center',
            backgroundColor: AppColors.navy,
            borderRadius: 40,
            overflow: 'hidden',
        },
        ctaTitle: {
            color: '#fff',
            fontFamily: AppFonts.bold,
            fontSize: isDesktop ? 60 : 36,
            textAlign: 'center',
            marginBottom: 24,
        },
        ctaSubtitle: {
            color: 'rgba(255,255,255,0.6)',
            fontFamily: AppFonts.regular,
            fontSize: 20,
            textAlign: 'center',
            maxWidth: 600,
            marginBottom: 48,
        },
        ctaButton: {
            backgroundColor: '#fff',
            paddingHorizontal: 40,
            paddingVertical: 20,
            borderRadius: 100,
        },
        ctaButtonText: {
            color: AppColors.navy,
            fontFamily: AppFonts.bold,
            fontSize: 18,
        },
        ctaMockups: {
            flexDirection: 'row',
            marginTop: 60,
            marginBottom: -100,
        },
        footer: {
            paddingTop: 100,
            paddingBottom: 40,
            backgroundColor: '#fff',
            paddingHorizontal: isDesktop ? 80 : 24,
        },
        footerTop: {
            flexDirection: isDesktop ? 'row' : 'column',
            justifyContent: 'space-between',
            maxWidth: 1400,
            alignSelf: 'center',
            width: '100%',
            gap: 60,
            marginBottom: 80,
        },
        footerBrand: {
            flex: 1,
        },
        footerLogo: {
            width: 140,
            height: 40,
            marginBottom: 20,
        },
        footerTagline: {
            color: AppColors.textSecondary,
            fontFamily: AppFonts.medium,
            fontSize: 16,
        },
        footerLinks: {
            flex: 2,
            flexDirection: 'row',
            justifyContent: 'space-around',
            gap: 40,
        },
        footerCol: {
            gap: 16,
        },
        footerColTitle: {
            fontFamily: AppFonts.bold,
            fontSize: 12,
            color: AppColors.navy,
            letterSpacing: 1.5,
            marginBottom: 8,
        },
        footerLink: {
            color: AppColors.textSecondary,
            fontFamily: AppFonts.medium,
            fontSize: 15,
        },
        footerBottom: {
            maxWidth: 1400,
            alignSelf: 'center',
            width: '100%',
            borderTopWidth: 1,
            borderTopColor: '#f1f5f9',
            paddingTop: 40,
            alignItems: 'center',
        },
        footerCopy: {
            color: 'rgba(15, 23, 42, 0.4)',
            fontSize: 14,
            textAlign: 'center',
        },
        glassCard: {
            borderRadius: 32,
            overflow: 'hidden',
            position: 'relative',
        },
        glassBackground: {
            ...StyleSheet.absoluteFillObject,
            backgroundColor: 'rgba(255,255,255,0.05)',
        },
        glassBorder: {
            ...StyleSheet.absoluteFillObject,
            borderWidth: 1,
            borderColor: 'rgba(255,255,255,0.08)',
            borderRadius: 32,
        },
        mockupWrapper: {
            alignItems: 'center',
        },
        deviceContainer: {
            width: 320,
            height: 650,
            position: 'relative',
        },
        deviceFrame: {
            width: '100%',
            height: '100%',
            backgroundColor: '#000',
            borderRadius: 44,
            padding: 12,
            borderWidth: 8,
            borderColor: '#1e293b',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 20 },
            shadowOpacity: 0.1,
            shadowRadius: 30,
        },
        deviceNotch: {
            position: 'absolute',
            top: 25,
            left: '50%',
            transform: [{ translateX: -40 }],
            width: 80,
            height: 25,
            backgroundColor: '#000',
            borderRadius: 15,
            zIndex: 10,
        },
        deviceScreen: {
            width: '100%',
            height: '100%',
            backgroundColor: '#000',
            borderRadius: 34,
            overflow: 'hidden',
        },
        deviceScreenImage: {
            width: '100%',
            height: '100%',
        },
        devicePlaceholder: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
        },
        devicePlaceholderText: {
            color: 'rgba(255,255,255,0.2)',
            fontFamily: AppFonts.bold,
            fontSize: 16,
            marginTop: 12,
        },
        deviceHomeBar: {
            position: 'absolute',
            bottom: 25,
            left: '50%',
            transform: [{ translateX: -40 }],
            width: 80,
            height: 4,
            backgroundColor: 'rgba(255,255,255,0.2)',
            borderRadius: 2,
        },
        deviceShadow: {
            position: 'absolute',
            bottom: -30,
            left: '10%',
            width: '80%',
            height: 40,
            backgroundColor: 'rgba(0,0,0,0.1)',
            borderRadius: 100,
            zIndex: -1,
        },
        deviceLabel: {
            marginTop: 24,
            fontFamily: AppFonts.bold,
            fontSize: 16,
            color: AppColors.navy,
            opacity: 0.8,
        },
    });
};
