import { CommunityPost } from '@/types/community';

export const mockPosts: CommunityPost[] = [
    {
        id: '1',
        userName: 'Chef Nattaya',
        userAvatar: 'https://i.pravatar.cc/150?img=1',
        image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600',
        caption: 'My Pad Thai turned out amazing today! 🍜 The secret is extra tamarind paste and fresh lime. Who else loves a good Pad Thai?',
        likes: 142,
        comments: 23,
        timeAgo: '2h ago',
        country: '🇹🇭 Thailand',
    },
    {
        id: '2',
        userName: 'Marco Rossi',
        userAvatar: 'https://i.pravatar.cc/150?img=3',
        image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600',
        caption: 'Nothing beats a homemade Margherita pizza from scratch! 🍕 San Marzano tomatoes are a game-changer.',
        likes: 287,
        comments: 41,
        timeAgo: '4h ago',
        country: '🇮🇹 Italy',
    },
    {
        id: '3',
        userName: 'Yuki Tanaka',
        userAvatar: 'https://i.pravatar.cc/150?img=5',
        image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600',
        caption: 'Sunday sushi making session 🍣 Made these California rolls with fresh salmon from the market!',
        likes: 198,
        comments: 32,
        timeAgo: '6h ago',
        country: '🇯🇵 Japan',
    },
    {
        id: '4',
        userName: 'Priya Sharma',
        userAvatar: 'https://i.pravatar.cc/150?img=9',
        image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600',
        caption: 'Butter chicken is comfort food at its finest ❤️ My grandma\'s recipe never disappoints. Recipe coming soon!',
        likes: 321,
        comments: 56,
        timeAgo: '8h ago',
        country: '🇮🇳 India',
    },
    {
        id: '5',
        userName: 'Soo-jin Park',
        userAvatar: 'https://i.pravatar.cc/150?img=10',
        image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600',
        caption: 'Dolsot bibimbap in a real stone pot 🔥 The crispy rice at the bottom is the best part!',
        likes: 176,
        comments: 28,
        timeAgo: '12h ago',
        country: '🇰🇷 Korea',
    },
    {
        id: '6',
        userName: 'David Chen',
        userAvatar: 'https://i.pravatar.cc/150?img=12',
        image: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=600',
        caption: 'Spent 12 hours on this tonkotsu broth and it was SO worth it 🍜 Rich, creamy, and packed with umami.',
        likes: 412,
        comments: 67,
        timeAgo: '1d ago',
        country: '🇯🇵 Japan',
    },
];
